Develop/v1.0.0 (#9)
* Release/v1.1.1 (#7)

* Features/v.1.1.1 (#1)

* Update ci.yaml

* Add files via upload

* Features/v.1.1.1 (#2)

* Update ci.yaml

* Add files via upload

* Update ci.yml

* Update ci.yml

* Update ci.yml

* Update IAM.json

* Update ci.yml

* Update ci.yml

* Update ci.yml

* Update ci.yml

* Update ci.yml

* Update IAM.json

* Update ci.yml

* Update IAM.json

* Update IAM.json (#8)

jj

* Update IAM.json

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,51 +1,116 @@
-name: CI
+name: CI-test
+
+permissions:
+  id-token: write
+  contents: read
 
 on:
-  workflow_dispatch: {}
+  workflow_dispatch:
+    inputs:
+      dry-run:
+        description: "Enable dry-run mode"
+        type: boolean
+        required: false
+        default: false
+      environment:
+        description: "Environment for dry-run"
+        type: choice
+        required: false
+        options:
+          - development
+          - staging
+          - production
 
   push:
-    branches:
-      - master
-      - "release/*"
-      - "develop/*"
-      - "features/*"
-      - "hotfixes/*"
     tags:
-      - "v*.*.*"
-      - "v*.*.*-rc*"
-    paths:
-      - functions/**
+      - "v[0-9]+.[0-9]+.[0-9]+"
+    branches:
+      - "develop/*"
+      - "release/*"
+      - main
+    paths-ignore:
+      - .azure-pipelines/**
+      - .github/**
+      - README.md
 
   pull_request:
     branches:
-      - master
-    paths:
-      - functions/**
+      - "develop/*"
+      - "release/*"
+      - main
+    types:
+      - opened
+      - synchronize
+      - reopened
+    paths-ignore:
+      - .azure-pipelines/**
+      - .github/**
+      - README.md
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+env:
+  IS_DEV: ${{ (inputs.dry-run && inputs.environment == 'development') || (!inputs.dry-run && ((github.event_name == 'pull_request' && startsWith(github.base_ref, 'develop')) || (github.event_name != 'pull_request' && github.ref_type == 'branch' && startsWith(github.ref_name, 'develop')))) }}
+  IS_STAGING: ${{ (inputs.dry-run && inputs.environment == 'staging') || (!inputs.dry-run && ((github.event_name == 'pull_request' && startsWith(github.base_ref, 'release')) || (github.event_name != 'pull_request' && github.ref_type == 'branch' && startsWith(github.ref_name, 'release')))) }}
+  IS_PROD: ${{ (inputs.dry-run && inputs.environment == 'production') || (!inputs.dry-run && ((github.event_name == 'pull_request' && github.base_ref == 'main') || (github.ref_type == 'tag' && !contains(github.ref_name, '-rc') && !contains(github.ref_name, '-qa')))) }}
+  envFile: ./.env
+
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  get-environment:
+    name: Get Environment
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
+    outputs:
+      result: ${{ steps.set-environment.outputs.result }}
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Set Environment Configuration
+        id: set-environment
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
-  check-branch:
+          obj=$(echo '{}' | jq -r '
+            if env.IS_DEV == "true" then {
+              result: "development"
+            } elif env.IS_STAGING == "true" then {
+              result: "staging"
+            } elif env.IS_PROD == "true" then {
+              result: "production"
+            } else {}
+            end
+          ')
+
+          if [ "$obj" == "{}" ]; then
+            echo "::error::Environment is not selected."
+            exit 1
+          fi
+
+          echo "result=$(echo "$obj" | jq -r '.result')" >> $GITHUB_OUTPUT
+          echo "::group::GITHUB_OUTPUT:"
+          cat $GITHUB_OUTPUT
+          echo "::endgroup::"
+
+  build:
+    name: Build ${{ needs.get-environment.outputs.result }}
     runs-on: ubuntu-latest
+    needs: get-environment
     steps:
-      - name: Check if branch starts with 'features'
-        if: github.ref_type == 'branch' && startsWith(github.ref_name, 'features') || startsWith(github.ref_name, 'hotfixes') || startsWith(github.ref_name, 'develop') || startsWith(github.ref_name, 'release') || github.ref_type == 'tag' || github.event_name == 'pull_request'
-        run: echo "Branch starts with 'features' "
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Load environment variables
+        run: |
+          if [ -f ${{ env.envFile }} ]; then
+            echo "Loading environment file ${{ env.envFile }}"
+            cat ${{ env.envFile }}
+          else
+            echo "No environment file found"
+          fi
+
+      - name: Print selected environment ${{needs.get-environment.outputs.result }}
+        run: echo "Building for environment"
+
+      - name: Build project
+        run: |
+          ENV="${{ needs.get-environment.outputs.result }}"
+          echo "Running build commands for $ENV"
+          # Add your actual build commands here
+          # For example:
+          # npm install
+          # npm run build:$ENV
+          
+          
